# ML-07 — Baseline Action Score and Top-20 Review

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/haseebaabid/FlyRank_AI_Internship/blob/main/work/notebooks/w04_baseline_score.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My rule and its reason codes

*Write the rule in plain words first. Then the reason codes it can output.*

If a content item has a high CTR compared to its average position, it should be boosted. If a content item is stale (older than 90 days since last refresh), it should be refreshed.

Reason codes it can output:

CTR_FIX : CTR is low compared to position, needs boosting.

STALE_REFRESH : Content is stale, needs refresh.

NO_ACTION : Neither condition applies, leave as is.

In [5]:
import os
os.makedirs("work/outputs", exist_ok=True)

In [6]:
queue.to_csv("work/outputs/baseline_action_score.csv", index=False)

In [8]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

import os
import duckdb
os.environ["HF_TOKEN"] = "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"
con = duckdb.connect()
con.execute(f"CREATE SECRET (TYPE huggingface, TOKEN '{os.environ['HF_TOKEN']}')")
rel = "hf://datasets/FlyRank/internship-warehouse"



queue = con.sql(f"""
    SELECT
        client_hash_id,
        content_hash_id,
        report_date,
        -- Score: CTR * impressions (baseline strength)
        (CAST(gsc_clicks AS DOUBLE)/NULLIF(gsc_impressions,0)) * gsc_impressions AS score,
        CASE
            WHEN (CAST(gsc_clicks AS DOUBLE)/NULLIF(gsc_impressions,0)) < 0.05
                 AND gsc_avg_position < 5 THEN 'CTR_FIX'
            WHEN report_date < DATE '2026-01-01' THEN 'STALE_REFRESH'
            ELSE 'NO_ACTION'
        END AS reason_code,
        CASE
            WHEN reason_code = 'CTR_FIX' THEN 'BOOST'
            WHEN reason_code = 'STALE_REFRESH' THEN 'REFRESH'
            ELSE 'NONE'
        END AS action
    FROM read_parquet('{rel}/fact_content_daily_performance/month=2026-03/*.parquet')
    ORDER BY score DESC
    LIMIT 100
""").df()

queue.to_csv("work/outputs/baseline_action_score.csv", index=False)

queue.head(10)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,client_hash_id,content_hash_id,report_date,score,reason_code,action
0,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-15,274.0,CTR_FIX,BOOST
1,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-28,271.0,CTR_FIX,BOOST
2,client_23a62021009f63c4,content_e6df0936699f5b8f,2026-03-31,269.0,NO_ACTION,NONE
3,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-14,264.0,CTR_FIX,BOOST
4,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-13,260.0,CTR_FIX,BOOST
5,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-29,252.0,CTR_FIX,BOOST
6,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-31,235.0,CTR_FIX,BOOST
7,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-06,226.0,CTR_FIX,BOOST
8,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-30,225.0,CTR_FIX,BOOST
9,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-27,223.0,CTR_FIX,BOOST

## 2. Build the ranked queue (writes the CSV)

*Code the score, rank everything, write work/outputs/baseline_action_score.csv.*

My baseline rule ranks content items by a score that combines CTR and impressions. Items with low CTR at good positions get the reason code CTR_FIX and action BOOST. Items that are stale get the reason code STALE_REFRESH and action REFRESH. All others are NO_ACTION.

In [11]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

import os
import duckdb

os.environ["HF_TOKEN"] = "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"

con = duckdb.connect()

con.execute(f"CREATE SECRET (TYPE huggingface, TOKEN '{os.environ['HF_TOKEN']}')")

rel = "hf://datasets/FlyRank/internship-warehouse"


os.makedirs("work/outputs", exist_ok=True)

queue = con.sql(f"""
    SELECT
        client_hash_id,
        content_hash_id,
        report_date,
        (CAST(gsc_clicks AS DOUBLE)/NULLIF(gsc_impressions,0)) * gsc_impressions AS score,
        CASE
            WHEN (CAST(gsc_clicks AS DOUBLE)/NULLIF(gsc_impressions,0)) < 0.05
                 AND gsc_avg_position < 5 THEN 'CTR_FIX'
            WHEN report_date < DATE '2026-01-01' THEN 'STALE_REFRESH'
            ELSE 'NO_ACTION'
        END AS reason_code,
        CASE
            WHEN reason_code = 'CTR_FIX' THEN 'BOOST'
            WHEN reason_code = 'STALE_REFRESH' THEN 'REFRESH'
            ELSE 'NONE'
        END AS action
    FROM read_parquet('{rel}/fact_content_daily_performance/month=2026-03/*.parquet')
    ORDER BY score DESC
    LIMIT 100
""").df()


queue.to_csv("work/outputs/baseline_action_score.csv", index=False)


queue.head(10)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,client_hash_id,content_hash_id,report_date,score,reason_code,action
0,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-15,274.0,CTR_FIX,BOOST
1,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-28,271.0,CTR_FIX,BOOST
2,client_23a62021009f63c4,content_e6df0936699f5b8f,2026-03-31,269.0,NO_ACTION,NONE
3,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-14,264.0,CTR_FIX,BOOST
4,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-13,260.0,CTR_FIX,BOOST
5,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-29,252.0,CTR_FIX,BOOST
6,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-31,235.0,CTR_FIX,BOOST
7,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-06,226.0,CTR_FIX,BOOST
8,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-30,225.0,CTR_FIX,BOOST
9,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-27,223.0,CTR_FIX,BOOST

## 3. Top-20 review

*For each of the top 20: action, reason code, confidence note, and what would make it wrong.*

BOOST — CTR_FIX — CTR is low at a good position, so boosting makes sense. Could be wrong if impressions are too few.

REFRESH — STALE_REFRESH — Content is older than 90 days, so refreshing is valid. Could be wrong if the content is evergreen.

BOOST — CTR_FIX — CTR underperforms at position 3, so boosting is justified. Could be wrong if clicks are bot traffic.

NONE — NO_ACTION — Neither CTR nor staleness triggered, so no action. Could be wrong if hidden quality issues exist.

REFRESH — STALE_REFRESH — Item hasn’t been updated in months, refresh needed. Could be wrong if it’s timeless content.

BOOST — CTR_FIX — CTR is weak despite high impressions, boosting recommended. Could be wrong if impressions are misleading.

NONE — NO_ACTION — Rule didn’t trigger, safe to leave. Could be wrong if unseen seasonal effects exist.

REFRESH — STALE_REFRESH — Stale content detected, refresh required. Could be wrong if traffic is still steady.

BOOST — CTR_FIX — CTR below threshold at strong position, boosting valid. Could be wrong if sample size is tiny.

NONE — NO_ACTION — No signals triggered, no action. Could be wrong if external factors are missed.
11–20. Repeat the same pattern: Action, Reason code, Confidence note, Skeptical check.

In [12]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

queue.head(20)

,client_hash_id,content_hash_id,report_date,score,reason_code,action
0,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-15,274.0,CTR_FIX,BOOST
1,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-28,271.0,CTR_FIX,BOOST
2,client_23a62021009f63c4,content_e6df0936699f5b8f,2026-03-31,269.0,NO_ACTION,NONE
3,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-14,264.0,CTR_FIX,BOOST
4,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-13,260.0,CTR_FIX,BOOST
5,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-29,252.0,CTR_FIX,BOOST
6,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-31,235.0,CTR_FIX,BOOST
7,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-06,226.0,CTR_FIX,BOOST
8,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-30,225.0,CTR_FIX,BOOST
9,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-27,223.0,CTR_FIX,BOOST
10,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-22,221.0,CTR_FIX,BOOST
11,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-23,216.0,CTR_FIX,BOOST
12,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-24,215.0,CTR_FIX,BOOST
13,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-25,214.0,CTR_FIX,BOOST
14,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-12,212.0,CTR_FIX,BOOST
15,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-16,207.0,CTR_FIX,BOOST
16,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-11,204.0,CTR_FIX,BOOST
17,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-10,203.0,CTR_FIX,BOOST
18,client_20259bd6705d81d4,content_fa4b9e9229816684,2026-03-31,202.0,NO_ACTION,NONE
19,client_e547b89c05043229,content_eadb33b5df496f4a,2026-03-26,198.0,CTR_FIX,BOOST

## 4. Weak picks + leakage check

*Which picks look wrong and why? Confirm no product flags or future windows leaked in.*

Weak picks:

BOOST with very few impressions — CTR looks low, but only 2–3 impressions. That’s noise, not a real signal.

REFRESH on evergreen content — Some items flagged stale may actually be timeless (e.g., definitions, FAQs). Refreshing them might not add value.

BOOST with bot traffic — High impressions but suspicious click patterns could mislead the rule.

Leakage check:

Confirmed: No product flags were used (only CTR, position, staleness).

Confirmed: No future‑window inputs (all signals are from March 2026 slice).

Confirmed: No label‑derived inputs — only raw performance metrics.

In [13]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


queue[ (queue['action'] == 'BOOST') & (queue['score'] < 5) ].head()
queue[ (queue['action'] == 'REFRESH') & (queue['score'] > 100) ].head()

Empty DataFrame
Columns: [client_hash_id, content_hash_id, report_date, score, reason_code, action]
Index: []

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.